#!/bin/bash
echo Hello
echo How are you?

echo -e "Hello\nHow are you?"

echo -e "\e[32mHello\n\e[33mHow are you?\n\e[0m"


# Color         # FG Color             # BG Color 
# Red             31                      41
# Green           32                      42  
# Yellow          33                      43
# Blue            34                      44
# Magenta         35                      45
# Cyan            36                      46

